const RED = 'red';
const YELLOW = '#ffca3a';
const LIGHT_GREEN = '#8ac926';
const PURPLE = '#6a4c93'
const DARK_BLUE = '#1982c4';
const PINK = '#ff595e';
const BLACK = 'black';

const CONSTANTS = {
  margin: 2,
  DEFAULT: [YELLOW, PINK, LIGHT_GREEN, PURPLE, BLACK],
  SORTED: [LIGHT_GREEN, RED, YELLOW, PURPLE, BLACK],
  PROCESSING: [DARK_BLUE, RED, LIGHT_GREEN, PURPLE, BLACK],
  CURRENT_MIN: [RED, YELLOW, DARK_BLUE, LIGHT_GREEN, BLACK],
  DELAY: 4, // SG 07/09/2022 13:54  4ms
}

export { CONSTANTS }