# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: yarn add typescript
    - run: CI=false yarn build
    
    - name: Deploying to Production Server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.UBUNTU_SERVER_SSH_SECRET }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "./build/"
        REMOTE_HOST: ${{ secrets.UBUNTU_SERVER_HOST }}
        REMOTE_USER: ${{ secrets.UBUNTU_SERVER_USERNAME }}
        TARGET: "~/algo-visualizer/"